### ISSUE TITLE
Platform case invalid in README.md

### ISSUE THREAD

**Issue by royto** [Icescreamlol/Garmin_Connect#1]
I have installed the custom components and I had an issue when trying to add the component into my configuration following instruction in the README.md. 

The error was that it could not found the garmin_connect component.

I change to Garmin_Connect and it's working now

So, i need to change my conf to : 

```yaml 
sensor: 
  - platform: Garmin_Connect
    username: XXXXXXXXXXXXXXXX 
    password: YYYYYYYYYYYYYYYY
```
